### ISSUE TITLE
TypeScript "declaration file"?

### ISSUE THREAD

**Issue by danwallach** [Daninet/gmp-wasm#2]
For what it's worth, I want to call this library from Kotlin, which apparently would be easier if there was a declaration file (`*.d.ts`). Not that I have any idea what that is, but I'm curious if it's on your agenda to make such a thing.

**Comment by Daninet** [comment]
It does have .d.ts files for the compiled bundles. They are pushed to NPM and it's also visible here on GitHub in the `binaries` branch. https://github.com/Daninet/gmp-wasm/tree/binaries/types/src
https://www.jsdelivr.com/package/npm/gmp-wasm?path=dist%2Ftypes%2Fsrc

Is there an extra step which needs to be done in order to make it work with Kotlin?

**Comment by danwallach** [comment]
Ahh, I didn't see that, because I was looking at the GitHub source. I'll figure this out. Supposedly, Kotlin has a tool that reads these declaration files.

**Comment by danwallach** [comment]
Well this is disappointing. The automatic TS to Kotlin interface extractor is... not very good. Like, it didn't notice any of the methods on an Integer, although it did figure out the `GMPLib` to `Context` part.

Like, this is the entirely of its extracted interface for `Integer`:
```kotlin
external interface IntegerFactory : IntegerFactoryReturn

external interface Integer : IntegerReturn

typealias OutputType<T> = Any

external enum class DivMode {
    CEIL /* = 0 */,
    FLOOR /* = 1 */,
    TRUNCATE /* = 2 */
}
```

Very disappointing. I can't tell you whether this is a problem on the TypeScript side (which I don't really understand) or with the Kotlin side (where the relevant tool is considered "alpha quality".

**Comment by Daninet** [comment]
The TypeScript interface works perfectly, I use it in production code.

The TypeScript declaration file looks like this.
```ts
declare type OutputType<T> = T extends number ? Integer : T extends Integer ? Integer : T extends Rational ? Rational : T extends Float ? Float : never;
export declare enum DivMode {
    CEIL = 0,
    FLOOR = 1,
    TRUNCATE = 2
}
```
I guess Kotlin cannot understand this more complicated declaration at OutputType which is required in order to have correct correct type inference when doing operations on mixed types. (Integer + Rational = Rational, Integer + Float = Float, etc...)

**Comment by danwallach** [comment]
The Kotlin is vaguely equivalent to the part you quoted, but what's missing is all of the actual methods on Integer (add, subtract, multiply, etc.). They're just not there in the generated Kotlin wrappers.

Needless to say, this means that I either have to do all that myself (error-prone, fragile, etc.), or I have to wait for the Kotlin tools to mature a bit.

**Comment by danwallach** [comment]
I've managed to figure out how to run `dukat` (the TypeScript-to-Kotlin interface extractor) manually and clean up its output, so I'm going to close this for now.
